### Upload catalog
PUT {{dbUrl}}/catalog/games-info.json?auth={{dbSecret}}
Content-Type: application/json

< catalog/games-info.json

###

### Upload lesnicka-palica
PUT {{dbUrl}}/games/lesnicka-palica.json?auth={{dbSecret}}
Content-Type: application/json

< games/lesnicka-palica.json

###

### Upload chorvatski-osadnici
PUT {{dbUrl}}/games/chorvatski-osadnici.json?auth={{dbSecret}}
Content-Type: application/json

< games/chorvatski-osadnici.json

###

### Upload danubiana-umenie-na-vode
PUT {{dbUrl}}/games/danubiana-umenie-na-vode.json?auth={{dbSecret}}
Content-Type: application/json

< games/danubiana-umenie-na-vode.json

###

### Upload rybar-z-drazdiaka
PUT {{dbUrl}}/games/rybar-z-drazdiaka.json?auth={{dbSecret}}
Content-Type: application/json

< games/rybar-z-drazdiaka.json

###

### Upload tajomstvo-janka-krala
PUT {{dbUrl}}/games/tajomstvo-janka-krala.json?auth={{dbSecret}}
Content-Type: application/json

< games/tajomstvo-janka-krala.json
