### Upload catalog
PUT {{dbUrl}}/catalog/games-info.json?auth={{dbSecret}}
Content-Type: application/json

< catalog/games-info.json

###

### Upload lesnicka-palica
PUT {{dbUrl}}/games/lesnicka-palica.json?auth={{dbSecret}}
Content-Type: application/json

< games/lesnicka-palica.json

###

### Upload rybar-z-drazdiaka
PUT {{dbUrl}}/games/rybar-z-drazdiaka.json?auth={{dbSecret}}
Content-Type: application/json

< games/rybar-z-drazdiaka.json

###

### Upload tajomstvo-janka-krala
PUT {{dbUrl}}/games/tajomstvo-janka-krala.json?auth={{dbSecret}}
Content-Type: application/json

< games/tajomstvo-janka-krala.json

###

### Upload vila-z-pecnianskeho-lesa
PUT {{dbUrl}}/games/vila-z-pecnianskeho-lesa.json?auth={{dbSecret}}
Content-Type: application/json

< games/vila-z-pecnianskeho-lesa.json

###

### Upload vodnik-z-chorvatskeho-ramena
PUT {{dbUrl}}/games/vodnik-z-chorvatskeho-ramena.json?auth={{dbSecret}}
Content-Type: application/json

< games/vodnik-z-chorvatskeho-ramena.json
